### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by atulonweb** [ashishd751/excel-renderer-demo#2]
This message comes in console after selecting excel file...

index.js:1 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://reactjs.org/link/controlled-components
    at input
    at Input (http://localhost:3001/static/js/vendors~main.chunk.js:115686:30)
    at div
    at InputGroup (http://localhost:3001/static/js/vendors~main.chunk.js:115814:25)
    at div
    at Col (http://localhost:3001/static/js/vendors~main.chunk.js:113855:25)
    at div
    at FormGroup (http://localhost:3001/static/js/vendors~main.chunk.js:115549:25)
    at form
    at div
    at Container (http://localhost:3001/static/js/vendors~main.chunk.js:114138:25)
    at div
    at Ppt (http://localhost:3001/static/js/main.chunk.js:1160:5)
    at div
    at Dashboard (http://localhost:3001/static/js/main.chunk.js:1718:1)
    at App (http://localhost:3001/static/js/main.chunk.js:186:5)
    at Route (http://localhost:3001/static/js/vendors~main.chunk.js:105398:29)
    at Switch (http://localhost:3001/static/js/vendors~main.chunk.js:105600:29)
    at Router (http://localhost:3001/static/js/vendors~main.chunk.js:105033:30)
    at BrowserRouter (http://localhost:3001/static/js/vendors~main.chunk.js:104653:35)
    at Router

**Comment by atulonweb** [comment]
There is alignment issue.. I am attaching screen shot of actual excel file and file getting displayed on browser.
Actual file
![image](https://user-images.githubusercontent.com/8655607/108820337-12004b80-75e2-11eb-9ea3-dbfac88bcb6b.png)

on browser
![image](https://user-images.githubusercontent.com/8655607/108820454-3825eb80-75e2-11eb-83e7-b9bc086794b3.png)

**Comment by atulonweb** [comment]
My configuration had problems... It is working properly
